<a href="https://colab.research.google.com/github/12honan/projects2/blob/main/simple_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
row = 1
while row <= 5:
  col = 1
  while col <= row:
    print(col, end=" ")
    col +=1
  row += 1
  print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
names = ["Harvy", "BOSS"]
ayy = ["gwapo","Plok plok"]
for name in names:
    for a in ayy:
      i = 0
    while i <=3:
        print(name,a, end=" ")
        i = i + 2
    print()

Harvy Plok plok Harvy Plok plok 
BOSS Plok plok BOSS Plok plok 


In [ ]:
names = ["Red", "maroon"]
ayy = ["Cherry","Raspberrie"]
for q in names:
  for s in ayy:
    u = 1
    while u <=2:
      print(q,s, )
      u = u+1


Red Cherry
Red Cherry
Red Raspberrie
Red Raspberrie
maroon Cherry
maroon Cherry
maroon Raspberrie
maroon Raspberrie


In [ ]:
# outer loop
for i in range(5):
    # nested loop
    # to iterate from 1 to 10
    for j in range(5):
        # print multiplication
        print(i + j, end=' ')
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 


In [ ]:
# outer loop
w = ["1","0"]
for i in w:
    # nested loop
    # to iterate from 1 to 10
    for j in w:
        u = 1
    while u <=10:
      print(i + j, end=" ")
      u = u+1
    print()
        # print multiplication


10 10 10 10 10 10 10 10 10 10 
00 00 00 00 00 00 00 00 00 00 


In [ ]:
import numpy
m = numpy.ones((3,5),dtype='int')
for row in m:
  print(row)

[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]


In [ ]:
array = np.random.randint(0, 10, size = (3,4,5))
array.shape
(3, 4, 5)
array
array([[[8, 8, 0, 6, 0],
        [9, 4, 6, 6, 1],
        [4, 3, 1, 3, 6],
        [2, 4, 4, 3, 9]],

       [[3, 5, 3, 9, 6],
        [8, 0, 8, 5, 3],
        [4, 8, 6, 2, 7],
        [2, 7, 1, 8, 4]],

       [[5, 7, 5, 6, 7],
        [7, 4, 2, 7, 0],
        [5, 6, 7, 9, 7],
        [7, 2, 7, 7, 4]]])
for elem in np.random.randiter(array):
  print(elem, end=' ')


NameError: ignored

In [ ]:
12/12

1.0

In [9]:
print("Instant Calculator")
print("\n")

rept = "yes"
while rept.lower() == "yes":

#the user will choose what operator they will use
  operator = input("PICK A LETTER FOR THE OPERATOR \n A.Addition + \n B.Subtraction -\n C.Multiplication x\n D.Division / \n E.Modulo % \n  >>>:  ")

#input the numbers want to solve
  num = int(input("Input the first number: "))
  num2 = int(input("Input the second number: "))

  if operator == 'A':
    print(num, "+", num2, '=', num+num2)
  elif operator == 'B':
    print(num, "-", num2, '=', num-num2)
  elif operator == 'C':
    print(num, "x", num2, '=', num*num2)
  elif operator == 'D':
    print(num, "÷", num2, '=', num/num2)
  elif operator == 'E':
    print(num, "&", num2, '=', num%num2)
  elif operator == "D":
    if num == 0 or num2 == 0:
      print(">>>Invalid")
  else:
    print(">>> ERROR")

  print("\n")
#loop if the user wants to calculate more
#if the user choose no the loop will break
  rept = input("do next calculation? yes or no: ")
  print("\n")
  if rept == "no":
    break

else :
  print(">>>> ERROR")

Instant Calculator


PICK A LETTER FOR THE OPERATOR 
 A.Addition + 
 B.Subtraction -
 C.Multiplication x
 D.Division / 
 E.Modulo % 
  >>>:  D
Input the first number: 123
Input the second number: 2
123 ÷ 2 = 61.5


do next calculation? yes or no: yes


PICK A LETTER FOR THE OPERATOR 
 A.Addition + 
 B.Subtraction -
 C.Multiplication x
 D.Division / 
 E.Modulo % 
  >>>:  C
Input the first number: 12
Input the second number: 12
12 x 12 = 144


do next calculation? yes or no: a


>>>> ERROR


In [ ]:
# Program make a simple calculator

# This function adds two numbers
def add(x, y):
    return x + y

# This function subtracts two numbers
def subtract(x, y):
    return x - y

# This function multiplies two numbers
def multiply(x, y):
    return x * y

# This function divides two numbers
def divide(x, y):
    return x / y


print("Select operation.")
print("1.Add")
print("2.Subtract")
print("3.Multiply")
print("4.Divide")

while True:
    # take input from the user
    choice = input("Enter choice(1/2/3/4): ")

    # check if choice is one of the four options
    if choice in ('1', '2', '3', '4'):
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        if choice == '1':
            print(num1, "+", num2, "=", add(num1, num2))

        elif choice == '2':
            print(num1, "-", num2, "=", subtract(num1, num2))

        elif choice == '3':
            print(num1, "*", num2, "=", multiply(num1, num2))

        elif choice == '4':
            print(num1, "/", num2, "=", divide(num1, num2))
        
        # check if user wants another calculation
        # break the while loop if answer is no
        next_calculation = input("Let's do next calculation? (yes/no): ")
        if next_calculation == "no":
          break
    
    else:
        print("Invalid Input")

Select operation.
1.Add
2.Subtract
3.Multiply
4.Divide
Enter choice(1/2/3/4): 1
Enter first number: 1
Enter second number: 1
1.0 + 1.0 = 2.0
Let's do next calculation? (yes/no): no


In [ ]:
cont = "y"
while cont.lower() == "y":
    print("Select operation\n1.Add\n2.Subtract\n3.Multiply\n4.Divide")

    choice = input("Enter choice(1/2/3/4):")

    num1 = int(input("Enter first number: "))
    num2 = int(input("Enter second number: "))

    if choice == '1':
       print(num1,"+",num2,"=", (num1 + num2))

    elif choice == '2':
       print(num1,"-",num2,"=", (num1 - num2))

    elif choice == '3':
       print(num1,"*",num2,"=", (num1 * num2))

    elif choice == '4':
       print(num1,"/",num2,"=", (num1 / num2))
    else:
       print("Invalid input")
    cont = input("Continue?y/n:")
    if cont == "n":
        break